# Generated by Django 4.0.6 on 2022-07-22 01:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_at_purchase', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0E-10'))])),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=23, validators=[django.core.validators.MinValueValidator(Decimal('0E-10'))])),
                ('entry_datetime', models.DateTimeField()),
            ],
        ),
    ]
