# Generated by Django 4.0.6 on 2022-08-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_assetentry_entry_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetentry',
            name='entry_datetime',
        ),
    ]
