# Generated by Django 4.0.6 on 2022-08-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_assetentry_entry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetentry',
            name='coingecko_id',
            field=models.CharField(default='coingecko_id', max_length=24),
            preserve_default=False,
        ),
    ]
