# Generated by Django 4.0.6 on 2022-08-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_assetentry_coingecko_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetentry',
            name='coingecko_id',
            field=models.CharField(default='', max_length=24),
        ),
    ]
