# Generated by Django 4.0.6 on 2022-11-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_assetentry_coingecko_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetentry',
            name='img_url',
            field=models.URLField(default='sample_url'),
        ),
    ]
