# Generated by Django 4.0.6 on 2022-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_assetentry_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetentry',
            name='img_url',
            field=models.URLField(default='#'),
        ),
    ]
